/**
 * The second tier of subcategory depth.
 *
 * `seed-taxonomy.mts` names the dozen-odd subcategories per sector a buyer
 * would reach for first. These are the rest — the ones somebody types when
 * they already know exactly what they want, which on a trade directory is most
 * people. A buyer searching "wafer butterfly valve DN200 PN16" is not browsing.
 *
 * Split into a second file only so neither is three hundred lines. They are
 * concatenated at the seed and are one list as far as the database is
 * concerned; nothing distinguishes a row here from a row there.
 *
 * The same rules apply: real trade nouns, Arabic on every row because
 * `Category.synonyms` routes queries in both languages, and two-letter codes
 * unique within their sector.
 */

import type { SubcategorySeed } from "./seed-taxonomy.mjs";

export const DEEP_SUBCATEGORIES: readonly SubcategorySeed[] = [
  // ── Valves & fittings ────────────────────────────────────────────────────
  { parent: "valves-and-fittings", slug: "plug-valves", code: "PG", name: "Plug valves", nameAr: "صمامات سدادة", synonyms: ["plug valve", "صمام سدادة"] },
  { parent: "valves-and-fittings", slug: "diaphragm-valves", code: "DG", name: "Diaphragm valves", nameAr: "صمامات غشائية", synonyms: ["diaphragm valve", "صمام غشائي"] },
  { parent: "valves-and-fittings", slug: "knife-gate-valves", code: "KG", name: "Knife gate valves", nameAr: "صمامات بوابة سكينية", synonyms: ["knife gate", "صمام سكيني"] },
  { parent: "valves-and-fittings", slug: "float-valves", code: "FV", name: "Float & level valves", nameAr: "صمامات العوامة", synonyms: ["float valve", "صمام عوامة"] },
  { parent: "valves-and-fittings", slug: "solenoid-valves", code: "SQ", name: "Solenoid valves", nameAr: "صمامات كهرومغناطيسية", synonyms: ["solenoid valve", "صمام سولينويد"] },
  { parent: "valves-and-fittings", slug: "control-valves", code: "CQ", name: "Control valves", nameAr: "صمامات التحكم", synonyms: ["control valve", "صمام تحكم", "modulating"] },
  { parent: "valves-and-fittings", slug: "air-release-valves", code: "AR", name: "Air release valves", nameAr: "صمامات تنفيس الهواء", synonyms: ["air release", "air valve", "صمام هواء"] },
  { parent: "valves-and-fittings", slug: "foot-valves", code: "FT", name: "Foot valves", nameAr: "صمامات القدم", synonyms: ["foot valve", "صمام قدم"] },
  { parent: "valves-and-fittings", slug: "balancing-valves", code: "BV2", name: "Balancing valves", nameAr: "صمامات الموازنة", synonyms: ["balancing valve", "صمام موازنة"] },
  { parent: "valves-and-fittings", slug: "fire-hydrant-valves", code: "FH", name: "Fire hydrant valves", nameAr: "صمامات حنفيات الحريق", synonyms: ["hydrant valve", "landing valve", "صمام حريق"] },
  { parent: "valves-and-fittings", slug: "instrumentation-fittings", code: "IF", name: "Instrumentation fittings", nameAr: "وصلات أجهزة القياس", synonyms: ["instrumentation fitting", "compression fitting", "وصلات قياس"] },
  { parent: "valves-and-fittings", slug: "hose-couplings", code: "HK", name: "Hose couplings", nameAr: "وصلات الخراطيم", synonyms: ["hose coupling", "camlock", "وصلة خرطوم"] },
  { parent: "valves-and-fittings", slug: "pressure-gauges", code: "PU", name: "Pressure gauges", nameAr: "مقاييس الضغط", synonyms: ["pressure gauge", "manometer", "مقياس ضغط"] },
  { parent: "valves-and-fittings", slug: "manifolds", code: "MF", name: "Manifolds", nameAr: "المشعبات", synonyms: ["manifold", "مشعب"] },
  { parent: "valves-and-fittings", slug: "valve-spares", code: "VS", name: "Valve spares & repair kits", nameAr: "قطع غيار الصمامات", synonyms: ["valve spares", "repair kit", "قطع غيار"] },
  { parent: "valves-and-fittings", slug: "sight-glasses", code: "SH", name: "Sight glasses", nameAr: "زجاج المراقبة", synonyms: ["sight glass", "زجاج مراقبة"] },
  { parent: "valves-and-fittings", slug: "bellows-seals", code: "BE", name: "Bellows-sealed valves", nameAr: "صمامات ذات منفاخ", synonyms: ["bellows seal", "صمام منفاخ"] },
  { parent: "valves-and-fittings", slug: "wafer-valves", code: "WV", name: "Wafer & lugged valves", nameAr: "صمامات ويفر", synonyms: ["wafer valve", "lugged", "ويفر"] },
  { parent: "valves-and-fittings", slug: "cryogenic-valves", code: "CG", name: "Cryogenic valves", nameAr: "صمامات التبريد العميق", synonyms: ["cryogenic valve", "lng valve", "صمام كريوجيني"] },
  { parent: "valves-and-fittings", slug: "sanitary-valves", code: "SY", name: "Sanitary & hygienic valves", nameAr: "صمامات صحية", synonyms: ["sanitary valve", "hygienic", "صمام صحي"] },
  { parent: "valves-and-fittings", slug: "butterfly-valve-spares", code: "BW", name: "Butterfly valve liners", nameAr: "بطانات الصمامات الفراشية", synonyms: ["butterfly liner", "epdm liner", "بطانة"] },
  { parent: "valves-and-fittings", slug: "forged-fittings", code: "FQ", name: "Forged fittings", nameAr: "وصلات مطروقة", synonyms: ["forged fitting", "socket weld", "وصلة مطروقة"] },
  { parent: "valves-and-fittings", slug: "victaulic-couplings", code: "VC", name: "Grooved couplings", nameAr: "وصلات محززة", synonyms: ["grooved coupling", "victaulic", "وصلة محززة"] },

  // ── Pipes & tubing ───────────────────────────────────────────────────────
  { parent: "pipes-and-tubing", slug: "carbon-steel-pipes", code: "CA", name: "Carbon steel pipes", nameAr: "أنابيب صلب كربوني", synonyms: ["carbon steel pipe", "a106", "صلب كربوني"] },
  { parent: "pipes-and-tubing", slug: "galvanised-fittings", code: "GF", name: "Galvanised fittings", nameAr: "وصلات مجلفنة", synonyms: ["gi fitting", "galvanised fitting", "وصلة مجلفنة"] },
  { parent: "pipes-and-tubing", slug: "pex-pipes", code: "PX", name: "PEX pipes", nameAr: "أنابيب بيكس", synonyms: ["pex", "cross linked", "بيكس"] },
  { parent: "pipes-and-tubing", slug: "cpvc-pipes", code: "CJ", name: "CPVC pipes", nameAr: "أنابيب سي بي في سي", synonyms: ["cpvc", "سي بي في سي"] },
  { parent: "pipes-and-tubing", slug: "hose-and-flexible", code: "HS", name: "Hoses & flexible pipe", nameAr: "خراطيم ومواسير مرنة", synonyms: ["hose", "flexible pipe", "خرطوم"] },
  { parent: "pipes-and-tubing", slug: "hydraulic-hose", code: "HY", name: "Hydraulic hose & fittings", nameAr: "خراطيم هيدروليكية", synonyms: ["hydraulic hose", "خرطوم هيدروليك"] },
  { parent: "pipes-and-tubing", slug: "pipe-coating", code: "PY", name: "Pipe coating & lining", nameAr: "طلاء وتبطين الأنابيب", synonyms: ["pipe coating", "3lpe", "lining", "طلاء أنابيب"] },
  { parent: "pipes-and-tubing", slug: "manholes-and-covers", code: "MK", name: "Manholes & covers", nameAr: "غرف التفتيش والأغطية", synonyms: ["manhole", "manhole cover", "غرفة تفتيش"] },
  { parent: "pipes-and-tubing", slug: "culverts", code: "CW", name: "Culverts & precast drainage", nameAr: "العبارات وتصريف مسبق الصب", synonyms: ["culvert", "precast drainage", "عبارة"] },
  { parent: "pipes-and-tubing", slug: "pipe-threading", code: "PB", name: "Pipe threading & cutting", nameAr: "قلاووظ وقص الأنابيب", synonyms: ["pipe threading", "pipe cutting", "قلاووظ"] },
  { parent: "pipes-and-tubing", slug: "aluminium-tubing", code: "AL", name: "Aluminium tubing", nameAr: "مواسير ألمنيوم", synonyms: ["aluminium tube", "ألمنيوم"] },
  { parent: "pipes-and-tubing", slug: "duplex-pipes", code: "DP", name: "Duplex & super duplex pipes", nameAr: "أنابيب دوبلكس", synonyms: ["duplex", "super duplex", "دوبلكس"] },
  { parent: "pipes-and-tubing", slug: "pipe-fabrication", code: "PN", name: "Pipe spool fabrication", nameAr: "تصنيع وحدات الأنابيب", synonyms: ["spool fabrication", "pipe fabrication", "تصنيع أنابيب"] },
  { parent: "pipes-and-tubing", slug: "trace-heating", code: "TH", name: "Trace heating", nameAr: "التسخين المصاحب", synonyms: ["trace heating", "heat tracing", "تسخين"] },
  { parent: "pipes-and-tubing", slug: "irrigation-pipes", code: "IR", name: "Irrigation pipes & drippers", nameAr: "أنابيب الري", synonyms: ["irrigation", "drip line", "ري"] },
  { parent: "pipes-and-tubing", slug: "compressed-air-pipe", code: "CI", name: "Compressed air piping", nameAr: "مواسير الهواء المضغوط", synonyms: ["compressed air pipe", "هواء مضغوط"] },
  { parent: "pipes-and-tubing", slug: "medical-gas-pipe", code: "MG", name: "Medical gas piping", nameAr: "مواسير الغازات الطبية", synonyms: ["medical gas", "غازات طبية"] },
  { parent: "pipes-and-tubing", slug: "pipe-testing", code: "PJ", name: "Pipe testing & inspection", nameAr: "فحص واختبار الأنابيب", synonyms: ["hydrotest", "ndt", "pipe testing", "فحص"] },
  { parent: "pipes-and-tubing", slug: "tubular-scaffolding", code: "TB", name: "Tubular sections", nameAr: "القطاعات الأنبوبية", synonyms: ["tubular section", "shs", "rhs", "قطاع أنبوبي"] },
  { parent: "pipes-and-tubing", slug: "pipe-cladding", code: "PD", name: "Pipe cladding", nameAr: "تكسية الأنابيب", synonyms: ["cladding", "aluminium cladding", "تكسية"] },
  { parent: "pipes-and-tubing", slug: "storm-water", code: "SZ", name: "Storm water systems", nameAr: "أنظمة مياه الأمطار", synonyms: ["storm water", "siphonic", "مياه أمطار"] },
  { parent: "pipes-and-tubing", slug: "pipe-valves-packages", code: "PW", name: "Piping packages", nameAr: "حزم الأنابيب", synonyms: ["piping package", "mto", "حزمة أنابيب"] },
  { parent: "pipes-and-tubing", slug: "fire-fighting-pipe", code: "FI", name: "Fire fighting pipe", nameAr: "مواسير مكافحة الحريق", synonyms: ["fire pipe", "ul fm pipe", "مواسير حريق"] },

  // ── HVAC & ventilation ───────────────────────────────────────────────────
  { parent: "hvac-and-ventilation", slug: "vrf-systems", code: "VR", name: "VRF & VRV systems", nameAr: "أنظمة تدفق المبرد المتغير", synonyms: ["vrf", "vrv", "تدفق متغير"] },
  { parent: "hvac-and-ventilation", slug: "ducted-splits", code: "DS", name: "Ducted split units", nameAr: "مكيفات مخفية", synonyms: ["ducted split", "concealed unit", "مكيف مخفي"] },
  { parent: "hvac-and-ventilation", slug: "chilled-water-pumps", code: "CZ", name: "Chilled water pumps", nameAr: "مضخات المياه المبردة", synonyms: ["chilled water pump", "مضخة مياه مبردة", "circulation pump"] },
  { parent: "hvac-and-ventilation", slug: "heat-exchangers", code: "HX", name: "Heat exchangers", nameAr: "المبادلات الحرارية", synonyms: ["heat exchanger", "plate exchanger", "مبادل حراري"] },
  { parent: "hvac-and-ventilation", slug: "air-filters", code: "AI", name: "Air filters", nameAr: "فلاتر الهواء", synonyms: ["air filter", "hepa", "فلتر هواء"] },
  { parent: "hvac-and-ventilation", slug: "duct-insulation", code: "DZ", name: "Duct insulation", nameAr: "عزل مجاري الهواء", synonyms: ["duct insulation", "عزل دكت"] },
  { parent: "hvac-and-ventilation", slug: "kitchen-ventilation", code: "KV", name: "Kitchen ventilation & hoods", nameAr: "تهوية المطابخ", synonyms: ["kitchen hood", "extraction", "شفاط مطبخ"] },
  { parent: "hvac-and-ventilation", slug: "car-park-ventilation", code: "PV2", name: "Car park ventilation", nameAr: "تهوية المواقف", synonyms: ["car park ventilation", "jet fan", "تهوية مواقف"] },
  { parent: "hvac-and-ventilation", slug: "smoke-extraction", code: "SX", name: "Smoke extraction", nameAr: "شفط الدخان", synonyms: ["smoke extraction", "smoke fan", "شفط دخان"] },
  { parent: "hvac-and-ventilation", slug: "dehumidifiers", code: "DH", name: "Dehumidifiers", nameAr: "مزيلات الرطوبة", synonyms: ["dehumidifier", "مزيل رطوبة"] },
  { parent: "hvac-and-ventilation", slug: "evaporative-coolers", code: "EC2", name: "Evaporative coolers", nameAr: "مبردات تبخيرية", synonyms: ["evaporative cooler", "مبرد صحراوي"] },
  { parent: "hvac-and-ventilation", slug: "district-cooling", code: "DL", name: "District cooling services", nameAr: "خدمات التبريد المركزي", synonyms: ["district cooling", "تبريد مركزي"] },
  { parent: "hvac-and-ventilation", slug: "refrigerants", code: "RG", name: "Refrigerants & gases", nameAr: "غازات التبريد", synonyms: ["refrigerant", "r410a", "غاز تبريد"] },
  { parent: "hvac-and-ventilation", slug: "compressors", code: "CQ2", name: "Compressors", nameAr: "الضواغط", synonyms: ["compressor", "ضاغط", "scroll compressor"] },
  { parent: "hvac-and-ventilation", slug: "condensing-units", code: "CN2", name: "Condensing units", nameAr: "وحدات التكثيف", synonyms: ["condensing unit", "وحدة تكثيف"] },
  { parent: "hvac-and-ventilation", slug: "display-chillers", code: "DX", name: "Display chillers & freezers", nameAr: "ثلاجات العرض", synonyms: ["display chiller", "freezer", "ثلاجة عرض"] },
  { parent: "hvac-and-ventilation", slug: "ice-machines", code: "IC", name: "Ice machines", nameAr: "ماكينات الثلج", synonyms: ["ice machine", "ماكينة ثلج"] },
  { parent: "hvac-and-ventilation", slug: "hvac-testing", code: "HT", name: "Testing & commissioning", nameAr: "الاختبار والتشغيل", synonyms: ["tab", "commissioning", "testing", "اختبار وتشغيل"] },
  { parent: "hvac-and-ventilation", slug: "energy-audits", code: "EU", name: "Energy audits & retrofit", nameAr: "تدقيق الطاقة", synonyms: ["energy audit", "retrofit", "تدقيق طاقة"] },
  { parent: "hvac-and-ventilation", slug: "water-treatment-hvac", code: "WQ", name: "HVAC water treatment", nameAr: "معالجة مياه التكييف", synonyms: ["water treatment", "dosing", "معالجة مياه"] },
  { parent: "hvac-and-ventilation", slug: "chiller-spares", code: "CY2", name: "Chiller spares", nameAr: "قطع غيار المبردات", synonyms: ["chiller spares", "قطع غيار مبردات"] },
  { parent: "hvac-and-ventilation", slug: "duct-fabrication", code: "DF", name: "Duct fabrication", nameAr: "تصنيع مجاري الهواء", synonyms: ["duct fabrication", "تصنيع دكت"] },
  { parent: "hvac-and-ventilation", slug: "cleanroom-hvac", code: "CH2", name: "Cleanroom HVAC", nameAr: "تكييف الغرف النظيفة", synonyms: ["cleanroom", "غرف نظيفة"] },

  // ── Electrical & cable ───────────────────────────────────────────────────
  { parent: "electrical-and-cable", slug: "fire-rated-cable", code: "FZ", name: "Fire-rated cable", nameAr: "كابلات مقاومة للحريق", synonyms: ["fire rated cable", "fp200", "كابل مقاوم للحريق"] },
  { parent: "electrical-and-cable", slug: "data-cable", code: "DA", name: "Data & fibre cable", nameAr: "كابلات البيانات والألياف", synonyms: ["fibre optic", "data cable", "كابل بيانات"] },
  { parent: "electrical-and-cable", slug: "cable-glands", code: "CJ2", name: "Cable glands & lugs", nameAr: "جلبات وأطراف الكابلات", synonyms: ["cable gland", "lug", "جلبة كابل"] },
  { parent: "electrical-and-cable", slug: "distribution-boards", code: "DB", name: "Distribution boards", nameAr: "لوحات التوزيع الفرعية", synonyms: ["distribution board", "db", "لوحة توزيع"] },
  { parent: "electrical-and-cable", slug: "capacitor-banks", code: "CB2", name: "Capacitor banks & PFC", nameAr: "مكثفات تحسين معامل القدرة", synonyms: ["capacitor bank", "power factor", "مكثفات"] },
  { parent: "electrical-and-cable", slug: "variable-speed-drives", code: "VD", name: "Variable speed drives", nameAr: "مغيرات السرعة", synonyms: ["vfd", "vsd", "inverter", "مغير سرعة"] },
  { parent: "electrical-and-cable", slug: "motors", code: "MO", name: "Electric motors", nameAr: "المحركات الكهربائية", synonyms: ["motor", "محرك كهربائي", "induction motor"] },
  { parent: "electrical-and-cable", slug: "solar-pv", code: "SP2", name: "Solar PV systems", nameAr: "أنظمة الطاقة الشمسية", synonyms: ["solar", "pv", "طاقة شمسية"] },
  { parent: "electrical-and-cable", slug: "emergency-lighting", code: "EL", name: "Emergency lighting", nameAr: "إنارة الطوارئ", synonyms: ["emergency light", "exit sign", "إنارة طوارئ"] },
  { parent: "electrical-and-cable", slug: "street-lighting", code: "SI", name: "Street & area lighting", nameAr: "إنارة الشوارع", synonyms: ["street light", "flood light", "إنارة شوارع"] },
  { parent: "electrical-and-cable", slug: "wiring-accessories", code: "WA", name: "Wiring accessories", nameAr: "ملحقات التمديدات", synonyms: ["switches", "sockets", "مفاتيح", "أفياش"] },
  { parent: "electrical-and-cable", slug: "electrical-testing", code: "ET", name: "Electrical testing", nameAr: "الاختبارات الكهربائية", synonyms: ["electrical testing", "thermography", "اختبار كهربائي"] },
  { parent: "electrical-and-cable", slug: "panel-building", code: "PB2", name: "Panel building", nameAr: "تصنيع اللوحات", synonyms: ["panel building", "assembly", "تصنيع لوحات"] },
  { parent: "electrical-and-cable", slug: "instrumentation", code: "IS", name: "Instrumentation & sensors", nameAr: "أجهزة القياس والحساسات", synonyms: ["instrumentation", "sensor", "transmitter", "حساس"] },
  { parent: "electrical-and-cable", slug: "plc-and-scada", code: "PS2", name: "PLC & SCADA", nameAr: "أنظمة التحكم الصناعي", synonyms: ["plc", "scada", "automation", "تحكم صناعي"] },
  { parent: "electrical-and-cable", slug: "atex-equipment", code: "AX", name: "Hazardous area equipment", nameAr: "معدات المناطق الخطرة", synonyms: ["atex", "explosion proof", "مناطق خطرة"] },
  { parent: "electrical-and-cable", slug: "cable-jointing", code: "CJ3", name: "Cable jointing & termination", nameAr: "وصل وإنهاء الكابلات", synonyms: ["cable jointing", "termination", "وصل كابلات"] },
  { parent: "electrical-and-cable", slug: "substations", code: "SB2", name: "Packaged substations", nameAr: "محطات فرعية جاهزة", synonyms: ["substation", "rmu", "محطة فرعية"] },
  { parent: "electrical-and-cable", slug: "energy-meters", code: "EE", name: "Energy meters", nameAr: "عدادات الطاقة", synonyms: ["energy meter", "kwh meter", "عداد كهرباء"] },
  { parent: "electrical-and-cable", slug: "surge-protection", code: "SG2", name: "Surge protection", nameAr: "الحماية من التيار الزائد", synonyms: ["surge protection", "spd", "حماية من الصواعق"] },
  { parent: "electrical-and-cable", slug: "cable-reels", code: "CE2", name: "Cable reels & drums", nameAr: "بكرات الكابلات", synonyms: ["cable reel", "بكرة كابل"] },
  { parent: "electrical-and-cable", slug: "electrical-tools", code: "EO", name: "Electrical tools", nameAr: "أدوات الكهرباء", synonyms: ["electrical tools", "crimping tool", "أدوات كهربائية"] },
  { parent: "electrical-and-cable", slug: "ev-charging", code: "EV", name: "EV charging", nameAr: "شواحن السيارات الكهربائية", synonyms: ["ev charger", "شاحن كهربائي"] },

  // ── Safety & PPE ─────────────────────────────────────────────────────────
  { parent: "safety-and-ppe", slug: "hearing-protection", code: "HN", name: "Hearing protection", nameAr: "حماية السمع", synonyms: ["ear plugs", "ear muffs", "واقي أذن"] },
  { parent: "safety-and-ppe", slug: "high-visibility", code: "HI", name: "High-visibility clothing", nameAr: "ملابس عالية الوضوح", synonyms: ["hi vis", "reflective vest", "سترة عاكسة"] },
  { parent: "safety-and-ppe", slug: "welding-safety", code: "WS", name: "Welding safety", nameAr: "سلامة اللحام", synonyms: ["welding helmet", "welding apron", "سلامة لحام"] },
  { parent: "safety-and-ppe", slug: "first-aid", code: "FI2", name: "First aid & medical kits", nameAr: "الإسعافات الأولية", synonyms: ["first aid", "medical kit", "إسعافات أولية"] },
  { parent: "safety-and-ppe", slug: "eyewash-stations", code: "EW", name: "Eyewash & safety showers", nameAr: "محطات غسيل العين", synonyms: ["eyewash", "safety shower", "غسيل عين"] },
  { parent: "safety-and-ppe", slug: "lockout-tagout", code: "LO", name: "Lockout / tagout", nameAr: "أنظمة العزل والوسم", synonyms: ["lockout", "tagout", "loto", "عزل"] },
  { parent: "safety-and-ppe", slug: "confined-space", code: "CF2", name: "Confined space equipment", nameAr: "معدات الأماكن المغلقة", synonyms: ["confined space", "tripod", "أماكن مغلقة"] },
  { parent: "safety-and-ppe", slug: "spill-control", code: "SL2", name: "Spill control", nameAr: "التحكم بالانسكاب", synonyms: ["spill kit", "absorbent", "انسكاب"] },
  { parent: "safety-and-ppe", slug: "safety-training", code: "SU2", name: "Safety training", nameAr: "تدريب السلامة", synonyms: ["safety training", "nebosh", "iosh", "تدريب سلامة"] },
  { parent: "safety-and-ppe", slug: "hse-consultancy", code: "HC2", name: "HSE consultancy", nameAr: "استشارات الصحة والسلامة", synonyms: ["hse consultancy", "safety audit", "استشارات سلامة"] },
  { parent: "safety-and-ppe", slug: "fire-doors", code: "FO", name: "Fire doors & shutters", nameAr: "أبواب الحريق", synonyms: ["fire door", "fire shutter", "باب حريق"] },
  { parent: "safety-and-ppe", slug: "fire-suppression", code: "FS", name: "Special hazard suppression", nameAr: "أنظمة الإطفاء الخاصة", synonyms: ["fm200", "novec", "clean agent", "إطفاء"] },
  { parent: "safety-and-ppe", slug: "fire-pumps", code: "FU", name: "Fire pumps", nameAr: "مضخات الحريق", synonyms: ["fire pump", "jockey pump", "مضخة حريق"] },
  { parent: "safety-and-ppe", slug: "public-address", code: "PE", name: "Public address & voice alarm", nameAr: "أنظمة النداء والإنذار الصوتي", synonyms: ["public address", "voice alarm", "نظام نداء"] },
  { parent: "safety-and-ppe", slug: "safety-signage", code: "SS2", name: "Safety signage", nameAr: "لافتات السلامة", synonyms: ["safety sign", "لافتة سلامة"] },
  { parent: "safety-and-ppe", slug: "traffic-management", code: "TG", name: "Traffic management", nameAr: "إدارة المرور", synonyms: ["traffic management", "road plates", "إدارة مرور"] },
  { parent: "safety-and-ppe", slug: "scaffold-safety", code: "SF2", name: "Scaffold safety", nameAr: "سلامة السقالات", synonyms: ["scaffold safety", "netting", "سلامة سقالات"] },
  { parent: "safety-and-ppe", slug: "site-welfare", code: "SW2", name: "Site welfare units", nameAr: "وحدات خدمات الموقع", synonyms: ["welfare unit", "portacabin", "كرفان"] },
  { parent: "safety-and-ppe", slug: "chemical-storage", code: "CS2", name: "Chemical storage", nameAr: "تخزين المواد الكيميائية", synonyms: ["chemical storage", "coshh cabinet", "تخزين كيماويات"] },
  { parent: "safety-and-ppe", slug: "marine-safety", code: "MS", name: "Marine safety", nameAr: "السلامة البحرية", synonyms: ["life jacket", "life raft", "سلامة بحرية"] },
  { parent: "safety-and-ppe", slug: "ppe-vending", code: "PV3", name: "PPE vending & consumables", nameAr: "مستهلكات معدات الوقاية", synonyms: ["ppe vending", "consumables", "مستهلكات"] },
  { parent: "safety-and-ppe", slug: "fire-extinguisher-refill", code: "FL2", name: "Extinguisher refilling", nameAr: "إعادة تعبئة الطفايات", synonyms: ["extinguisher refill", "تعبئة طفايات"] },
  { parent: "safety-and-ppe", slug: "safety-nets", code: "SN2", name: "Safety nets & barriers", nameAr: "شبكات وحواجز الأمان", synonyms: ["safety net", "barrier", "شبكة أمان"] },

  // ── Packaging & materials ────────────────────────────────────────────────
  { parent: "packaging-and-materials", slug: "paper-bags", code: "PP2", name: "Paper bags & sacks", nameAr: "أكياس ورقية", synonyms: ["paper bag", "kraft sack", "كيس ورق"] },
  { parent: "packaging-and-materials", slug: "plastic-bags", code: "PB3", name: "Plastic bags & liners", nameAr: "أكياس بلاستيكية", synonyms: ["plastic bag", "liner", "كيس بلاستيك"] },
  { parent: "packaging-and-materials", slug: "bottles-and-jars", code: "BJ", name: "Bottles & jars", nameAr: "زجاجات وبرطمانات", synonyms: ["bottle", "jar", "pet bottle", "زجاجة"] },
  { parent: "packaging-and-materials", slug: "caps-and-closures", code: "CC2", name: "Caps & closures", nameAr: "أغطية وسدادات", synonyms: ["cap", "closure", "غطاء"] },
  { parent: "packaging-and-materials", slug: "cans-and-tins", code: "CT2", name: "Cans & tins", nameAr: "علب معدنية", synonyms: ["can", "tin", "علبة معدنية"] },
  { parent: "packaging-and-materials", slug: "void-fill", code: "VF2", name: "Void fill & cushioning", nameAr: "مواد الحشو", synonyms: ["void fill", "cushioning", "حشو"] },
  { parent: "packaging-and-materials", slug: "desiccants", code: "DE", name: "Desiccants & moisture control", nameAr: "مواد امتصاص الرطوبة", synonyms: ["desiccant", "silica gel", "مجفف"] },
  { parent: "packaging-and-materials", slug: "coding-and-marking", code: "CD2", name: "Coding & marking", nameAr: "الترميز والوسم", synonyms: ["coding", "inkjet printer", "batch coding", "ترميز"] },
  { parent: "packaging-and-materials", slug: "shrink-tunnels", code: "SH2", name: "Shrink tunnels & wrappers", nameAr: "أنفاق التغليف الحراري", synonyms: ["shrink tunnel", "wrapper", "تغليف حراري"] },
  { parent: "packaging-and-materials", slug: "filling-machines", code: "FM2", name: "Filling machines", nameAr: "ماكينات التعبئة", synonyms: ["filling machine", "ماكينة تعبئة"] },
  { parent: "packaging-and-materials", slug: "weighing-equipment", code: "WE", name: "Weighing equipment", nameAr: "معدات الوزن", synonyms: ["weighing scale", "platform scale", "ميزان"] },
  { parent: "packaging-and-materials", slug: "conveyors", code: "CV2", name: "Conveyors", nameAr: "السيور الناقلة", synonyms: ["conveyor", "belt conveyor", "سير ناقل"] },
  { parent: "packaging-and-materials", slug: "mezzanine-floors", code: "MZ", name: "Mezzanine floors", nameAr: "الأدوار الوسطية", synonyms: ["mezzanine", "ميزانين"] },
  { parent: "packaging-and-materials", slug: "shelving-systems", code: "SY2", name: "Shelving systems", nameAr: "أنظمة الرفوف", synonyms: ["shelving", "long span", "رفوف"] },
  { parent: "packaging-and-materials", slug: "plastic-crates", code: "PC2", name: "Plastic crates & bins", nameAr: "صناديق بلاستيكية", synonyms: ["crate", "bin", "صندوق بلاستيك"] },
  { parent: "packaging-and-materials", slug: "wooden-cases", code: "WC", name: "Wooden cases & crating", nameAr: "صناديق خشبية", synonyms: ["wooden case", "export crate", "صندوق خشب"] },
  { parent: "packaging-and-materials", slug: "raw-plastics", code: "RW", name: "Raw plastics & resins", nameAr: "المواد البلاستيكية الخام", synonyms: ["resin", "granules", "hdpe resin", "بوليمر"] },
  { parent: "packaging-and-materials", slug: "paper-and-board", code: "PR2", name: "Paper & board", nameAr: "الورق والكرتون", synonyms: ["paper", "board", "duplex board", "ورق"] },
  { parent: "packaging-and-materials", slug: "adhesives", code: "AD", name: "Adhesives & sealants", nameAr: "المواد اللاصقة", synonyms: ["adhesive", "sealant", "لاصق"] },
  { parent: "packaging-and-materials", slug: "industrial-chemicals", code: "IH", name: "Industrial chemicals", nameAr: "الكيماويات الصناعية", synonyms: ["industrial chemical", "solvent", "كيماويات"] },
  { parent: "packaging-and-materials", slug: "cleaning-chemicals", code: "CK2", name: "Cleaning chemicals", nameAr: "مواد التنظيف", synonyms: ["cleaning chemical", "detergent", "منظفات"] },
  { parent: "packaging-and-materials", slug: "recycled-packaging", code: "RE", name: "Recycled & sustainable packaging", nameAr: "التغليف المستدام", synonyms: ["recycled packaging", "sustainable", "تغليف مستدام"] },
  { parent: "packaging-and-materials", slug: "stationery", code: "SA2", name: "Office stationery", nameAr: "القرطاسية", synonyms: ["stationery", "office supplies", "قرطاسية"] },

  // ── Construction & building materials ────────────────────────────────────
  { parent: "construction-and-building-materials", slug: "precast-concrete", code: "PE2", name: "Precast concrete", nameAr: "الخرسانة مسبقة الصب", synonyms: ["precast", "hollow core", "مسبق الصب"] },
  { parent: "construction-and-building-materials", slug: "concrete-admixtures", code: "AM", name: "Concrete admixtures", nameAr: "إضافات الخرسانة", synonyms: ["admixture", "plasticiser", "إضافات خرسانة"] },
  { parent: "construction-and-building-materials", slug: "asphalt", code: "AP", name: "Asphalt & road works", nameAr: "الأسفلت وأعمال الطرق", synonyms: ["asphalt", "road works", "أسفلت"] },
  { parent: "construction-and-building-materials", slug: "structural-steel-sections", code: "SS3", name: "Structural steel sections", nameAr: "المقاطع الحديدية الإنشائية", synonyms: ["i beam", "h beam", "channel", "مقاطع حديد"] },
  { parent: "construction-and-building-materials", slug: "roofing", code: "RO", name: "Roofing & cladding", nameAr: "الأسقف والتكسيات", synonyms: ["roofing", "sandwich panel", "cladding", "أسقف"] },
  { parent: "construction-and-building-materials", slug: "aluminium-fabrication", code: "AU2", name: "Aluminium fabrication", nameAr: "تصنيع الألمنيوم", synonyms: ["aluminium fabrication", "تصنيع ألمنيوم"] },
  { parent: "construction-and-building-materials", slug: "marble-and-granite", code: "MA", name: "Marble & granite", nameAr: "الرخام والجرانيت", synonyms: ["marble", "granite", "رخام", "جرانيت"] },
  { parent: "construction-and-building-materials", slug: "sanitary-ware", code: "SW3", name: "Sanitary ware & fittings", nameAr: "الأدوات الصحية", synonyms: ["sanitary ware", "أدوات صحية", "wc", "basin"] },
  { parent: "construction-and-building-materials", slug: "kitchens-and-wardrobes", code: "KW", name: "Kitchens & wardrobes", nameAr: "المطابخ والخزائن", synonyms: ["kitchen", "wardrobe", "مطبخ", "خزانة"] },
  { parent: "construction-and-building-materials", slug: "interior-fitout", code: "IN2", name: "Interior fit-out", nameAr: "التشطيبات الداخلية", synonyms: ["fit out", "interior", "تشطيبات", "joinery"] },
  { parent: "construction-and-building-materials", slug: "civil-contracting", code: "CC3", name: "Civil contracting", nameAr: "المقاولات المدنية", synonyms: ["civil contractor", "مقاولات", "contracting"] },
  { parent: "construction-and-building-materials", slug: "mep-contracting", code: "MP2", name: "MEP contracting", nameAr: "مقاولات الأعمال الكهروميكانيكية", synonyms: ["mep contractor", "mep", "كهروميكانيك"] },
  { parent: "construction-and-building-materials", slug: "demolition", code: "DO", name: "Demolition & dismantling", nameAr: "الهدم والتفكيك", synonyms: ["demolition", "هدم"] },
  { parent: "construction-and-building-materials", slug: "piling-and-foundations", code: "PF2", name: "Piling & foundations", nameAr: "الخوازيق والأساسات", synonyms: ["piling", "foundation", "خوازيق"] },
  { parent: "construction-and-building-materials", slug: "surveying", code: "SV2", name: "Surveying & setting out", nameAr: "المساحة", synonyms: ["surveying", "topographic", "مساحة"] },
  { parent: "construction-and-building-materials", slug: "soil-testing", code: "SO2", name: "Soil & material testing", nameAr: "فحص التربة والمواد", synonyms: ["soil testing", "material testing", "فحص تربة"] },
  { parent: "construction-and-building-materials", slug: "architectural-services", code: "AS", name: "Architectural & engineering design", nameAr: "التصميم المعماري والهندسي", synonyms: ["architect", "engineering consultant", "تصميم معماري"] },
  { parent: "construction-and-building-materials", slug: "project-management", code: "PJ2", name: "Project management", nameAr: "إدارة المشاريع", synonyms: ["project management", "pmc", "إدارة مشاريع"] },
  { parent: "construction-and-building-materials", slug: "quantity-surveying", code: "QS", name: "Quantity surveying", nameAr: "مسح الكميات", synonyms: ["quantity surveyor", "cost consultant", "مسح كميات"] },
  { parent: "construction-and-building-materials", slug: "swimming-pool-construction", code: "SP3", name: "Swimming pool construction", nameAr: "إنشاء المسابح", synonyms: ["pool construction", "بناء مسابح"] },
  { parent: "construction-and-building-materials", slug: "fencing-and-gates", code: "FG2", name: "Fencing & gates", nameAr: "الأسوار والبوابات", synonyms: ["fencing", "gate", "سور", "بوابة"] },
  { parent: "construction-and-building-materials", slug: "shoring", code: "SR2", name: "Shoring & excavation support", nameAr: "دعم الحفريات", synonyms: ["shoring", "sheet pile", "دعم حفريات"] },
  { parent: "construction-and-building-materials", slug: "false-flooring", code: "FF2", name: "Raised & false flooring", nameAr: "الأرضيات المرتفعة", synonyms: ["raised floor", "access floor", "أرضيات مرتفعة"] },

  // ── Logistics & freight forwarding ───────────────────────────────────────
  { parent: "logistics-and-freight", slug: "container-trading", code: "CO2", name: "Container sales & leasing", nameAr: "بيع وتأجير الحاويات", synonyms: ["container sales", "container leasing", "حاويات"] },
  { parent: "logistics-and-freight", slug: "bonded-warehousing", code: "BW2", name: "Bonded warehousing", nameAr: "المستودعات الجمركية", synonyms: ["bonded warehouse", "مستودع جمركي"] },
  { parent: "logistics-and-freight", slug: "fulfilment", code: "FL3", name: "E-commerce fulfilment", nameAr: "خدمات التجارة الإلكترونية", synonyms: ["fulfilment", "e-commerce logistics", "تجارة إلكترونية"] },
  { parent: "logistics-and-freight", slug: "dangerous-goods", code: "DG2", name: "Dangerous goods handling", nameAr: "مناولة البضائع الخطرة", synonyms: ["dangerous goods", "dg cargo", "بضائع خطرة"] },
  { parent: "logistics-and-freight", slug: "livestock-transport", code: "LI", name: "Livestock & perishables", nameAr: "نقل المواشي والمواد سريعة التلف", synonyms: ["livestock", "perishable", "مواشي"] },
  { parent: "logistics-and-freight", slug: "crane-and-rigging", code: "CR2", name: "Crane hire & rigging", nameAr: "تأجير الرافعات", synonyms: ["crane hire", "rigging", "رافعة"] },
  { parent: "logistics-and-freight", slug: "port-services", code: "PT2", name: "Port & terminal services", nameAr: "خدمات الموانئ", synonyms: ["port services", "stevedoring", "موانئ"] },
  { parent: "logistics-and-freight", slug: "cargo-insurance", code: "CI2", name: "Cargo insurance", nameAr: "تأمين البضائع", synonyms: ["cargo insurance", "تأمين شحن"] },
  { parent: "logistics-and-freight", slug: "inspection-services", code: "IN3", name: "Cargo inspection & survey", nameAr: "فحص البضائع", synonyms: ["cargo inspection", "surveyor", "فحص بضائع"] },
  { parent: "logistics-and-freight", slug: "fleet-management", code: "FE2", name: "Fleet management", nameAr: "إدارة الأساطيل", synonyms: ["fleet management", "telematics", "إدارة أسطول"] },
  { parent: "logistics-and-freight", slug: "car-shipping", code: "CS3", name: "Vehicle shipping", nameAr: "شحن السيارات", synonyms: ["car shipping", "roro", "شحن سيارات"] },
  { parent: "logistics-and-freight", slug: "packing-services", code: "PK2", name: "Export packing", nameAr: "التغليف للتصدير", synonyms: ["export packing", "تغليف تصدير"] },
  { parent: "logistics-and-freight", slug: "document-clearance", code: "DQ", name: "Documentation & certificates", nameAr: "المستندات والشهادات", synonyms: ["certificate of origin", "documentation", "شهادة منشأ"] },
  { parent: "logistics-and-freight", slug: "reverse-logistics", code: "RL", name: "Reverse logistics", nameAr: "اللوجستيات العكسية", synonyms: ["reverse logistics", "returns", "مرتجعات"] },
  { parent: "logistics-and-freight", slug: "yard-management", code: "YM", name: "Yard & open storage", nameAr: "التخزين المكشوف", synonyms: ["open yard", "yard storage", "ساحة تخزين"] },
  { parent: "logistics-and-freight", slug: "cross-docking", code: "CX2", name: "Cross docking", nameAr: "التحميل المباشر", synonyms: ["cross docking", "تحميل مباشر"] },
  { parent: "logistics-and-freight", slug: "rail-freight", code: "RA", name: "Rail freight", nameAr: "الشحن بالسكك الحديدية", synonyms: ["rail freight", "etihad rail", "شحن سكك"] },
  { parent: "logistics-and-freight", slug: "bulk-cargo", code: "BU", name: "Bulk & break-bulk cargo", nameAr: "البضائع السائبة", synonyms: ["bulk cargo", "break bulk", "بضائع سائبة"] },
  { parent: "logistics-and-freight", slug: "tank-transport", code: "TT", name: "Tanker & liquid transport", nameAr: "نقل السوائل", synonyms: ["tanker", "liquid transport", "نقل سوائل"] },
  { parent: "logistics-and-freight", slug: "logistics-consultancy", code: "LG2", name: "Supply chain consultancy", nameAr: "استشارات سلسلة التوريد", synonyms: ["supply chain consultancy", "استشارات لوجستية"] },
  { parent: "logistics-and-freight", slug: "wms-software", code: "WM2", name: "Warehouse management systems", nameAr: "أنظمة إدارة المستودعات", synonyms: ["wms", "warehouse software", "نظام مستودعات"] },
  { parent: "logistics-and-freight", slug: "labour-and-loaders", code: "LB", name: "Loading & unloading labour", nameAr: "عمالة التحميل والتفريغ", synonyms: ["loaders", "unloading", "عمالة تحميل"] },
  { parent: "logistics-and-freight", slug: "airport-handling", code: "AH2", name: "Airport ground handling", nameAr: "المناولة الأرضية", synonyms: ["ground handling", "مناولة أرضية"] },

  // ── Facilities management & cleaning ─────────────────────────────────────
  { parent: "facilities-management-and-cleaning", slug: "residential-cleaning", code: "RC", name: "Residential cleaning", nameAr: "تنظيف المنازل", synonyms: ["home cleaning", "maid service", "تنظيف منازل"] },
  { parent: "facilities-management-and-cleaning", slug: "post-construction-cleaning", code: "PO2", name: "Post-construction cleaning", nameAr: "التنظيف بعد البناء", synonyms: ["post construction cleaning", "تنظيف بعد البناء"] },
  { parent: "facilities-management-and-cleaning", slug: "carpet-and-upholstery", code: "CU2", name: "Carpet & upholstery cleaning", nameAr: "تنظيف السجاد والمفروشات", synonyms: ["carpet cleaning", "upholstery", "تنظيف سجاد"] },
  { parent: "facilities-management-and-cleaning", slug: "disinfection", code: "DI2", name: "Disinfection & sanitisation", nameAr: "التعقيم", synonyms: ["disinfection", "sanitisation", "تعقيم"] },
  { parent: "facilities-management-and-cleaning", slug: "grease-trap", code: "GP", name: "Grease trap & drainage cleaning", nameAr: "تنظيف مصائد الشحوم", synonyms: ["grease trap", "drain cleaning", "مصيدة شحوم"] },
  { parent: "facilities-management-and-cleaning", slug: "septic-tank", code: "SE2", name: "Septic tank services", nameAr: "خدمات خزانات الصرف", synonyms: ["septic tank", "sewage tanker", "خزان صرف"] },
  { parent: "facilities-management-and-cleaning", slug: "plumbing-services", code: "PL2", name: "Plumbing services", nameAr: "خدمات السباكة", synonyms: ["plumbing", "plumber", "سباكة"] },
  { parent: "facilities-management-and-cleaning", slug: "electrical-services", code: "EL2", name: "Electrical services", nameAr: "خدمات الكهرباء", synonyms: ["electrician", "electrical service", "كهربائي"] },
  { parent: "facilities-management-and-cleaning", slug: "painting-services", code: "PA2", name: "Painting & decorating", nameAr: "خدمات الدهان", synonyms: ["painting service", "decorating", "دهان"] },
  { parent: "facilities-management-and-cleaning", slug: "handyman", code: "HM", name: "Handyman services", nameAr: "خدمات الصيانة العامة", synonyms: ["handyman", "صيانة عامة"] },
  { parent: "facilities-management-and-cleaning", slug: "generator-maintenance", code: "GM", name: "Generator maintenance", nameAr: "صيانة المولدات", synonyms: ["generator maintenance", "صيانة مولدات"] },
  { parent: "facilities-management-and-cleaning", slug: "fire-system-maintenance", code: "FY", name: "Fire system maintenance", nameAr: "صيانة أنظمة الحريق", synonyms: ["fire system maintenance", "صيانة حريق"] },
  { parent: "facilities-management-and-cleaning", slug: "energy-management", code: "EG", name: "Energy management", nameAr: "إدارة الطاقة", synonyms: ["energy management", "إدارة طاقة"] },
  { parent: "facilities-management-and-cleaning", slug: "cafeteria-services", code: "CA2", name: "Catering & cafeteria services", nameAr: "خدمات المطاعم والكافتيريا", synonyms: ["cafeteria", "staff catering", "كافتيريا"] },
  { parent: "facilities-management-and-cleaning", slug: "corporate-catering", code: "CO3", name: "Corporate catering", nameAr: "التموين المؤسسي", synonyms: ["corporate catering", "event catering", "تموين"] },
  { parent: "facilities-management-and-cleaning", slug: "reception-services", code: "RN", name: "Reception & concierge", nameAr: "خدمات الاستقبال", synonyms: ["reception", "concierge", "استقبال"] },
  { parent: "facilities-management-and-cleaning", slug: "office-furniture", code: "OF2", name: "Office furniture", nameAr: "أثاث المكاتب", synonyms: ["office furniture", "أثاث مكتبي"] },
  { parent: "facilities-management-and-cleaning", slug: "moving-and-storage", code: "MV", name: "Office moving", nameAr: "نقل المكاتب", synonyms: ["office moving", "نقل مكاتب"] },
  { parent: "facilities-management-and-cleaning", slug: "car-park-management", code: "CP2", name: "Car park management", nameAr: "إدارة المواقف", synonyms: ["car park management", "valet", "إدارة مواقف"] },
  { parent: "facilities-management-and-cleaning", slug: "building-inspection", code: "BI", name: "Building inspection & snagging", nameAr: "فحص المباني", synonyms: ["snagging", "building inspection", "فحص مباني"] },
  { parent: "facilities-management-and-cleaning", slug: "pool-and-fountain", code: "PU2", name: "Fountain maintenance", nameAr: "صيانة النوافير", synonyms: ["fountain maintenance", "نوافير"] },
  { parent: "facilities-management-and-cleaning", slug: "irrigation-maintenance", code: "IG", name: "Irrigation maintenance", nameAr: "صيانة أنظمة الري", synonyms: ["irrigation maintenance", "صيانة ري"] },
  { parent: "facilities-management-and-cleaning", slug: "waste-recycling", code: "WR", name: "Recycling services", nameAr: "خدمات إعادة التدوير", synonyms: ["recycling", "scrap", "إعادة تدوير"] },

  // ── Printing, signage & events ───────────────────────────────────────────
  { parent: "printing-signage-and-events", slug: "business-cards", code: "BC", name: "Business cards & stationery print", nameAr: "طباعة القرطاسية", synonyms: ["business cards", "letterhead", "كروت"] },
  { parent: "printing-signage-and-events", slug: "brochures-and-catalogues", code: "BR", name: "Brochures & catalogues", nameAr: "الكتيبات والكتالوجات", synonyms: ["brochure", "catalogue", "كتيب"] },
  { parent: "printing-signage-and-events", slug: "roll-up-banners", code: "RU", name: "Roll-ups & pop-ups", nameAr: "الرول أب", synonyms: ["roll up", "pop up", "رول أب"] },
  { parent: "printing-signage-and-events", slug: "acrylic-fabrication", code: "AK", name: "Acrylic fabrication", nameAr: "تصنيع الأكريليك", synonyms: ["acrylic", "perspex", "أكريليك"] },
  { parent: "printing-signage-and-events", slug: "neon-and-led-signs", code: "NE", name: "Neon & LED signs", nameAr: "لافتات النيون والليد", synonyms: ["neon sign", "led sign", "نيون"] },
  { parent: "printing-signage-and-events", slug: "wayfinding", code: "WF", name: "Wayfinding & directories", nameAr: "لوحات الإرشاد", synonyms: ["wayfinding", "directory sign", "إرشاد"] },
  { parent: "printing-signage-and-events", slug: "shop-fitting", code: "SF3", name: "Shop fitting & retail displays", nameAr: "تجهيز المحلات", synonyms: ["shop fitting", "retail display", "تجهيز محلات"] },
  { parent: "printing-signage-and-events", slug: "furniture-rental", code: "FR2", name: "Event furniture rental", nameAr: "تأجير أثاث الفعاليات", synonyms: ["furniture rental", "تأجير أثاث"] },
  { parent: "printing-signage-and-events", slug: "tents-and-marquees", code: "TE", name: "Tents & marquees", nameAr: "الخيام والمظلات", synonyms: ["tent", "marquee", "خيمة"] },
  { parent: "printing-signage-and-events", slug: "led-screens", code: "LE", name: "LED screens & displays", nameAr: "شاشات الليد", synonyms: ["led screen", "display", "شاشة ليد"] },
  { parent: "printing-signage-and-events", slug: "event-staffing", code: "ES", name: "Event staffing", nameAr: "طاقم الفعاليات", synonyms: ["event staff", "hostess", "طاقم فعاليات"] },
  { parent: "printing-signage-and-events", slug: "catering-equipment-rental", code: "CE3", name: "Catering equipment rental", nameAr: "تأجير معدات التموين", synonyms: ["catering equipment", "تأجير معدات"] },
  { parent: "printing-signage-and-events", slug: "audio-visual-production", code: "AO", name: "Video & film production", nameAr: "إنتاج الفيديو", synonyms: ["film production", "video production", "إنتاج"] },
  { parent: "printing-signage-and-events", slug: "3d-printing", code: "TD", name: "3D printing & prototyping", nameAr: "الطباعة ثلاثية الأبعاد", synonyms: ["3d printing", "prototyping", "طباعة ثلاثية"] },
  { parent: "printing-signage-and-events", slug: "engraving", code: "EQ", name: "Engraving & laser cutting", nameAr: "الحفر والقص بالليزر", synonyms: ["engraving", "laser cutting", "حفر ليزر"] },
  { parent: "printing-signage-and-events", slug: "trophies-and-awards", code: "TW", name: "Trophies & awards", nameAr: "الدروع والجوائز", synonyms: ["trophy", "award", "درع"] },
  { parent: "printing-signage-and-events", slug: "flags-and-banners", code: "FB2", name: "Flags & banners", nameAr: "الأعلام واللافتات", synonyms: ["flag", "banner", "علم"] },
  { parent: "printing-signage-and-events", slug: "digital-marketing", code: "DK", name: "Digital marketing", nameAr: "التسويق الرقمي", synonyms: ["digital marketing", "seo", "تسويق رقمي"] },
  { parent: "printing-signage-and-events", slug: "pr-agencies", code: "PU3", name: "PR & communications", nameAr: "العلاقات العامة", synonyms: ["public relations", "pr agency", "علاقات عامة"] },
  { parent: "printing-signage-and-events", slug: "translation-services", code: "TS", name: "Copywriting & translation", nameAr: "كتابة المحتوى والترجمة", synonyms: ["copywriting", "translation", "ترجمة"] },
  { parent: "printing-signage-and-events", slug: "wide-format-media", code: "WD", name: "Print media & consumables", nameAr: "مواد الطباعة", synonyms: ["print media", "ink", "vinyl", "أحبار"] },
  { parent: "printing-signage-and-events", slug: "screen-printing", code: "SP4", name: "Screen printing", nameAr: "طباعة الشاشة الحريرية", synonyms: ["screen printing", "silk screen", "سلك سكرين"] },
  { parent: "printing-signage-and-events", slug: "book-binding", code: "BD", name: "Binding & finishing", nameAr: "التجليد والتشطيب", synonyms: ["binding", "lamination", "تجليد"] },

  // ── IT, telecom & software ───────────────────────────────────────────────
  { parent: "it-telecom-and-software", slug: "laptops-and-desktops", code: "LP", name: "Laptops & desktops", nameAr: "أجهزة الحاسب", synonyms: ["laptop", "desktop", "pc", "حاسوب"] },
  { parent: "it-telecom-and-software", slug: "printers-and-copiers", code: "PC3", name: "Printers & copiers", nameAr: "الطابعات وآلات النسخ", synonyms: ["printer", "copier", "mfp", "طابعة"] },
  { parent: "it-telecom-and-software", slug: "it-consumables", code: "IU", name: "IT consumables", nameAr: "مستهلكات تقنية", synonyms: ["toner", "cartridge", "حبر"] },
  { parent: "it-telecom-and-software", slug: "data-centre", code: "DN", name: "Data centre infrastructure", nameAr: "بنية مراكز البيانات", synonyms: ["data centre", "rack", "مركز بيانات"] },
  { parent: "it-telecom-and-software", slug: "backup-and-dr", code: "BK", name: "Backup & disaster recovery", nameAr: "النسخ الاحتياطي", synonyms: ["backup", "disaster recovery", "نسخ احتياطي"] },
  { parent: "it-telecom-and-software", slug: "crm-software", code: "CM2", name: "CRM software", nameAr: "أنظمة إدارة العملاء", synonyms: ["crm", "salesforce", "إدارة عملاء"] },
  { parent: "it-telecom-and-software", slug: "hr-software", code: "HW", name: "HR & payroll software", nameAr: "أنظمة الموارد البشرية", synonyms: ["hr software", "payroll software", "نظام موارد بشرية"] },
  { parent: "it-telecom-and-software", slug: "mobile-app-development", code: "MB", name: "Mobile app development", nameAr: "تطوير تطبيقات الجوال", synonyms: ["mobile app", "ios", "android", "تطبيقات"] },
  { parent: "it-telecom-and-software", slug: "web-design", code: "WB", name: "Web design & development", nameAr: "تصميم المواقع", synonyms: ["web design", "website", "تصميم مواقع"] },
  { parent: "it-telecom-and-software", slug: "ecommerce-platforms", code: "EO2", name: "E-commerce platforms", nameAr: "منصات التجارة الإلكترونية", synonyms: ["ecommerce", "online store", "متجر إلكتروني"] },
  { parent: "it-telecom-and-software", slug: "it-staffing", code: "IT2", name: "IT staffing & outsourcing", nameAr: "توظيف وإسناد تقني", synonyms: ["it staffing", "outsourcing", "توظيف تقني"] },
  { parent: "it-telecom-and-software", slug: "digital-transformation", code: "DT", name: "Digital transformation consulting", nameAr: "استشارات التحول الرقمي", synonyms: ["digital transformation", "تحول رقمي"] },
  { parent: "it-telecom-and-software", slug: "gps-tracking", code: "GT2", name: "GPS & vehicle tracking", nameAr: "تتبع المركبات", synonyms: ["gps tracking", "vehicle tracking", "تتبع"] },
  { parent: "it-telecom-and-software", slug: "time-attendance", code: "TA2", name: "Time & attendance systems", nameAr: "أنظمة الحضور والانصراف", synonyms: ["time attendance", "biometric", "حضور وانصراف"] },
  { parent: "it-telecom-and-software", slug: "queue-management", code: "QM", name: "Queue management systems", nameAr: "أنظمة إدارة الطوابير", synonyms: ["queue management", "إدارة طوابير"] },
  { parent: "it-telecom-and-software", slug: "digital-signage-software", code: "DJ", name: "Digital signage systems", nameAr: "أنظمة اللافتات الرقمية", synonyms: ["digital signage", "لافتات رقمية"] },
  { parent: "it-telecom-and-software", slug: "smart-home", code: "SM2", name: "Smart home & building automation", nameAr: "أتمتة المباني", synonyms: ["smart home", "building automation", "أتمتة"] },
  { parent: "it-telecom-and-software", slug: "intercom-systems", code: "IK", name: "Intercom & video door entry", nameAr: "أنظمة الاتصال الداخلي", synonyms: ["intercom", "video door phone", "انتركم"] },
  { parent: "it-telecom-and-software", slug: "gate-barriers", code: "GB", name: "Gate barriers & turnstiles", nameAr: "البوابات والحواجز", synonyms: ["barrier", "turnstile", "boom gate", "بوابة"] },
  { parent: "it-telecom-and-software", slug: "it-relocation", code: "IL", name: "IT relocation & installation", nameAr: "نقل وتركيب الأنظمة", synonyms: ["it relocation", "installation", "تركيب أنظمة"] },
  { parent: "it-telecom-and-software", slug: "software-licensing", code: "SG3", name: "Software licensing", nameAr: "تراخيص البرمجيات", synonyms: ["software licence", "microsoft", "تراخيص"] },
  { parent: "it-telecom-and-software", slug: "data-analytics", code: "DY", name: "Data analytics & BI", nameAr: "تحليل البيانات", synonyms: ["analytics", "business intelligence", "تحليل بيانات"] },
  { parent: "it-telecom-and-software", slug: "ai-services", code: "AZ", name: "AI & automation services", nameAr: "خدمات الذكاء الاصطناعي", synonyms: ["ai", "machine learning", "ذكاء اصطناعي"] },

  // ── Legal, audit & business setup ────────────────────────────────────────
  { parent: "legal-audit-and-business-setup", slug: "free-zone-setup", code: "FZ2", name: "Free zone company setup", nameAr: "تأسيس شركات المناطق الحرة", synonyms: ["free zone setup", "ifza", "dmcc", "منطقة حرة"] },
  { parent: "legal-audit-and-business-setup", slug: "mainland-setup", code: "MN", name: "Mainland company setup", nameAr: "تأسيس شركات البر الرئيسي", synonyms: ["mainland setup", "ded licence", "بر رئيسي"] },
  { parent: "legal-audit-and-business-setup", slug: "offshore-setup", code: "OS", name: "Offshore company setup", nameAr: "تأسيس الشركات الخارجية", synonyms: ["offshore", "rak icc", "أوفشور"] },
  { parent: "legal-audit-and-business-setup", slug: "bank-account-opening", code: "BO", name: "Corporate bank account opening", nameAr: "فتح الحسابات المصرفية", synonyms: ["bank account opening", "فتح حساب بنكي"] },
  { parent: "legal-audit-and-business-setup", slug: "internal-audit", code: "IA2", name: "Internal audit", nameAr: "التدقيق الداخلي", synonyms: ["internal audit", "تدقيق داخلي"] },
  { parent: "legal-audit-and-business-setup", slug: "due-diligence", code: "DD", name: "Due diligence", nameAr: "العناية الواجبة", synonyms: ["due diligence", "عناية واجبة"] },
  { parent: "legal-audit-and-business-setup", slug: "valuation-services", code: "VL", name: "Business & asset valuation", nameAr: "تقييم الأصول", synonyms: ["valuation", "asset valuation", "تقييم"] },
  { parent: "legal-audit-and-business-setup", slug: "liquidation", code: "LQ", name: "Company liquidation", nameAr: "تصفية الشركات", synonyms: ["liquidation", "deregistration", "تصفية"] },
  { parent: "legal-audit-and-business-setup", slug: "corporate-tax", code: "CT3", name: "Corporate tax compliance", nameAr: "امتثال ضريبة الشركات", synonyms: ["corporate tax", "ضريبة شركات"] },
  { parent: "legal-audit-and-business-setup", slug: "excise-tax", code: "EX2", name: "Excise tax", nameAr: "الضريبة الانتقائية", synonyms: ["excise tax", "ضريبة انتقائية"] },
  { parent: "legal-audit-and-business-setup", slug: "transfer-pricing", code: "TZ", name: "Transfer pricing", nameAr: "تسعير المعاملات", synonyms: ["transfer pricing", "تسعير تحويلي"] },
  { parent: "legal-audit-and-business-setup", slug: "esr-and-ubo", code: "EB", name: "ESR & UBO compliance", nameAr: "الامتثال التنظيمي", synonyms: ["esr", "ubo", "goaml", "امتثال"] },
  { parent: "legal-audit-and-business-setup", slug: "arbitration", code: "AN", name: "Arbitration & dispute resolution", nameAr: "التحكيم وحل النزاعات", synonyms: ["arbitration", "dispute resolution", "تحكيم"] },
  { parent: "legal-audit-and-business-setup", slug: "contract-drafting", code: "CQ3", name: "Contract drafting & review", nameAr: "صياغة العقود", synonyms: ["contract drafting", "صياغة عقود"] },
  { parent: "legal-audit-and-business-setup", slug: "employment-law", code: "EY", name: "Employment law", nameAr: "قانون العمل", synonyms: ["employment law", "labour law", "قانون عمل"] },
  { parent: "legal-audit-and-business-setup", slug: "real-estate-law", code: "RD", name: "Real estate & conveyancing", nameAr: "القانون العقاري", synonyms: ["real estate law", "conveyancing", "قانون عقاري"] },
  { parent: "legal-audit-and-business-setup", slug: "debt-collection", code: "DU", name: "Debt collection", nameAr: "تحصيل الديون", synonyms: ["debt collection", "تحصيل ديون"] },
  { parent: "legal-audit-and-business-setup", slug: "notary-services", code: "NO", name: "Notary & legalisation", nameAr: "التوثيق والتصديق", synonyms: ["notary", "legalisation", "كاتب عدل"] },
  { parent: "legal-audit-and-business-setup", slug: "insurance-brokerage", code: "IB", name: "Insurance brokerage", nameAr: "وساطة التأمين", synonyms: ["insurance broker", "وسيط تأمين"] },
  { parent: "legal-audit-and-business-setup", slug: "cfo-services", code: "CO4", name: "Outsourced CFO services", nameAr: "خدمات المدير المالي", synonyms: ["cfo services", "virtual cfo", "مدير مالي"] },
  { parent: "legal-audit-and-business-setup", slug: "recruitment-agencies", code: "RQ", name: "Recruitment agencies", nameAr: "وكالات التوظيف", synonyms: ["recruitment", "headhunting", "توظيف"] },
  { parent: "legal-audit-and-business-setup", slug: "training-and-development", code: "TN", name: "Corporate training", nameAr: "التدريب المؤسسي", synonyms: ["corporate training", "تدريب"] },
  { parent: "legal-audit-and-business-setup", slug: "iso-certification", code: "IO", name: "ISO certification & consultancy", nameAr: "شهادات الأيزو", synonyms: ["iso certification", "iso 9001", "أيزو"] },
];
