-- Board 11g — the tax invoice, which is the only screen on the platform that is
-- a legal document.
--
-- Additive throughout: one table, two enums, fourteen columns, four constraints.
-- Nothing is dropped and nothing on an existing table becomes NOT NULL, so this
-- applies **before** the merge (docs/deployments.md § Ordering) and the running
-- deployment carries on reading a schema that still satisfies it.
--
-- Four things the board states that the model could not hold:
--
--   1. **The supplier, stored.** The issuing entity is Bearing Deployment
--      Company, Inc — Delaware, San Francisco — not the UAE company the board
--      was first drawn with, and it has **no TRN**. Reading our own identity
--      from a constant means a re-registration silently rewrites every invoice
--      ever issued; this entity has already been restated once, so that is an
--      argument from events rather than in principle.
--
--   2. **Per-line VAT.** A single blended `VAT 5%` row is right for an invoice
--      whose lines are all standard-rated and wrong as a document design: the
--      first zero-rated, exempt or out-of-scope line has nowhere to go, and a
--      document's layout cannot change after issue.
--
--   3. **Three dates, not one.** The board printed `14 AUG 2026` once and let it
--      stand for date of issue, date of supply and the supply period together.
--      Each is separately mandatory on a tax document.
--
--   4. **`invoice_event`.** The delivery log — where it was emailed and who
--      downloaded it. Deliberately not `audit_event`, whose `reason` is NOT NULL
--      because it records decisions staff make; nobody decides to download their
--      own invoice.
--
-- Every statement is idempotent. `migrate dev` regenerates hand-written DDL and
-- drops what it did not author otherwise.

-- ── 1 · the supplier, as at issue ──────────────────────────────────────────
-- No TRN column, and its absence is the point: an unlabelled tax number beside
-- the recipient's would read as the issuer's.
ALTER TABLE "invoice" ADD COLUMN IF NOT EXISTS "supplier_name"          TEXT;
ALTER TABLE "invoice" ADD COLUMN IF NOT EXISTS "supplier_address"       TEXT;
ALTER TABLE "invoice" ADD COLUMN IF NOT EXISTS "supplier_incorporation" TEXT;

-- ── 2 · the dates and the supply ───────────────────────────────────────────
ALTER TABLE "invoice" ADD COLUMN IF NOT EXISTS "supply_date"     TIMESTAMP(3);
ALTER TABLE "invoice" ADD COLUMN IF NOT EXISTS "place_of_supply" TEXT;
ALTER TABLE "invoice" ADD COLUMN IF NOT EXISTS "currency"        TEXT NOT NULL DEFAULT 'AED';

-- ── 3 · the references printed under the totals ────────────────────────────
ALTER TABLE "invoice" ADD COLUMN IF NOT EXISTS "psp_ref"          TEXT;
ALTER TABLE "invoice" ADD COLUMN IF NOT EXISTS "subscription_ref" TEXT;

-- ── 4 · the PDF written at issue ───────────────────────────────────────────
-- The download serves this file, byte for byte. A PDF regenerated by a later
-- template is a different document from the one the seller filed with their
-- accountant, even when every figure matches.
ALTER TABLE "invoice" ADD COLUMN IF NOT EXISTS "pdf_path"  TEXT;
ALTER TABLE "invoice" ADD COLUMN IF NOT EXISTS "pdf_bytes" INTEGER;

-- Both or neither. A path with no size is a file nothing can report on, and a
-- size with no path is a number about nothing.
ALTER TABLE "invoice" DROP CONSTRAINT IF EXISTS "invoice_pdf_together";
ALTER TABLE "invoice" ADD CONSTRAINT "invoice_pdf_together" CHECK (
  ("pdf_path" IS NULL AND "pdf_bytes" IS NULL)
  OR ("pdf_path" IS NOT NULL AND "pdf_bytes" IS NOT NULL)
);

-- ── 5 · how a line is treated for VAT ──────────────────────────────────────
DO $$
BEGIN
  CREATE TYPE "tax_treatment" AS ENUM ('standard', 'zero_rated', 'exempt', 'out_of_scope');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

ALTER TABLE "invoice_line"
  ADD COLUMN IF NOT EXISTS "tax_treatment" "tax_treatment" NOT NULL DEFAULT 'standard';

-- ── 6 · per-line VAT and the unit price ────────────────────────────────────
-- Nullable and deliberately not backfilled. A line written before this migration
-- has no stored unit price or line VAT, and deriving one now from today's rate
-- would be indistinguishable on screen from one that was actually charged —
-- which is the property these columns exist to provide. The renderer reads a
-- null as "not stored" and says so.
ALTER TABLE "invoice_line" ADD COLUMN IF NOT EXISTS "unit_aed"    DECIMAL(12,2);
ALTER TABLE "invoice_line" ADD COLUMN IF NOT EXISTS "vat_rate"    DECIMAL(4,4);
ALTER TABLE "invoice_line" ADD COLUMN IF NOT EXISTS "vat_aed"     DECIMAL(12,2);
ALTER TABLE "invoice_line" ADD COLUMN IF NOT EXISTS "booking_ref" TEXT;

-- A rate outside 0–1 is a percentage that has reached the database as a whole
-- number, which would multiply a line by a hundred.
ALTER TABLE "invoice_line" DROP CONSTRAINT IF EXISTS "invoice_line_vat_rate_range";
ALTER TABLE "invoice_line" ADD CONSTRAINT "invoice_line_vat_rate_range" CHECK (
  "vat_rate" IS NULL OR ("vat_rate" >= 0 AND "vat_rate" <= 1)
);

-- A line that states a rate states what it produced, and the other way round.
-- Either the pair is stored or neither is: half of it cannot be rendered.
ALTER TABLE "invoice_line" DROP CONSTRAINT IF EXISTS "invoice_line_vat_together";
ALTER TABLE "invoice_line" ADD CONSTRAINT "invoice_line_vat_together" CHECK (
  ("vat_rate" IS NULL AND "vat_aed" IS NULL)
  OR ("vat_rate" IS NOT NULL AND "vat_aed" IS NOT NULL)
);

-- ── 7 · the delivery log ───────────────────────────────────────────────────
DO $$
BEGIN
  CREATE TYPE "invoice_event_kind" AS ENUM ('emailed', 'downloaded');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS "invoice_event" (
  "id"         TEXT NOT NULL,
  "invoice_id" TEXT NOT NULL,
  "kind"       "invoice_event_kind" NOT NULL,
  "recipient"  TEXT,
  "actor_id"   UUID,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "invoice_event_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "invoice_event" DROP CONSTRAINT IF EXISTS "invoice_event_invoice_id_fkey";
ALTER TABLE "invoice_event" ADD CONSTRAINT "invoice_event_invoice_id_fkey"
  FOREIGN KEY ("invoice_id") REFERENCES "invoice"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- `SET NULL`, not `CASCADE`. A person leaving does not un-send an invoice, and
-- the delivery log has to keep saying it went out.
ALTER TABLE "invoice_event" DROP CONSTRAINT IF EXISTS "invoice_event_actor_id_fkey";
ALTER TABLE "invoice_event" ADD CONSTRAINT "invoice_event_actor_id_fkey"
  FOREIGN KEY ("actor_id") REFERENCES "user"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

CREATE INDEX IF NOT EXISTS "invoice_event_invoice_idx"
  ON "invoice_event" ("invoice_id", "created_at" DESC);

-- An email that names nobody is a row that cannot answer the question the panel
-- exists to answer. A download names no recipient, by definition.
ALTER TABLE "invoice_event" DROP CONSTRAINT IF EXISTS "invoice_event_recipient_when_emailed";
ALTER TABLE "invoice_event" ADD CONSTRAINT "invoice_event_recipient_when_emailed" CHECK (
  ("kind" = 'emailed' AND "recipient" IS NOT NULL)
  OR ("kind" = 'downloaded' AND "recipient" IS NULL)
);

-- ── 8 · where invoices go ──────────────────────────────────────────────────
-- Board 7e owns the billing address and had no column for it, so `11g`'s
-- delivery panel would have claimed "billing address comes from Settings" about
-- a setting that did not exist. Nullable, and null is the ordinary state:
-- `billingRecipient()` resolves the finance seat and then the owner, which is
-- an answer the platform already holds rather than a field most sellers would
-- leave empty.
ALTER TABLE "notification_preference" ADD COLUMN IF NOT EXISTS "billing_email" TEXT;
