import { describe, expect, it } from "vitest";
import {
  FilenameIndex,
  keysFor,
  normaliseFilename,
  splitFilenames,
  stemOf,
  stripUploadSuffix,
} from "@/lib/import/filenames";
import { safeName } from "@/lib/storage/buckets";

/**
 * Board 11d criterion 7, and the reason it could not work as drawn.
 *
 * The render says `405 of 412 filenames are in your media library`. Matching a
 * CSV cell against `basename(storage_path)` would have said `0 of 412`, because
 * `safeName` appends six random characters to every upload — and it would have
 * said it in a sentence that reads like an answer.
 */

describe("normaliseFilename", () => {
  it("normalises the way safeName does", () => {
    expect(normaliseFilename("  Valve DN100.png ")).toBe("valve-dn100.png");
    expect(normaliseFilename("BF/100.JPG").endsWith(".jpg")).toBe(true);
  });

  /*
     The invariant the whole module rests on, asserted against the real
     function rather than against a string I typed out.

     These two have to agree about what counts as the same name — they are the
     only two places in the codebase that decide it, and a change to either
     without the other silently stops every photo matching. Awkward names on
     purpose: brackets, spaces, a double separator and mixed case are what a
     seller's photo folder actually looks like.
  */
  it.each([
    "BF-100.jpg",
    "BF-100 (1).JPG",
    "Butterfly Valve — DN100.png",
    "img_0042.JPEG",
    "datasheet.v2.pdf",
  ])("agrees with safeName about %s", (original) => {
    const stored = safeName(original);
    // safeName's output, with the suffix it added taken back off.
    const withoutSuffix = stripUploadSuffix(stemOf(stored)) + stored.slice(stored.lastIndexOf("."));
    expect(normaliseFilename(original)).toBe(withoutSuffix);
  });

  it("takes the last segment of a path, because a cell often holds one", () => {
    expect(normaliseFilename("C:\\photos\\bf-100.jpg")).toBe("bf-100.jpg");
    expect(normaliseFilename("images/sub/bf-100.jpg")).toBe("bf-100.jpg");
  });
});

describe("stripUploadSuffix", () => {
  it("removes what safeName added", () => {
    expect(stripUploadSuffix("bf-100-x7k2m9")).toBe("bf-100");
  });

  it("leaves something to match on when the name is only a suffix", () => {
    expect(stripUploadSuffix("abc123")).toBe("abc123");
  });
});

describe("FilenameIndex", () => {
  it("matches a file uploaded through safeName, which is the whole point", () => {
    // The real path a real upload produces, generated by the real function.
    const storagePath = `biz-1/gallery/${safeName("BF-100.jpg")}`;
    const index = new FilenameIndex([{ id: "m1", filename: "BF-100.jpg", storagePath }]);

    expect(index.match("BF-100.jpg")).toEqual({ kind: "matched", id: "m1" });
    // And the way a seller actually types it into a spreadsheet.
    expect(index.match("bf-100.JPG")).toEqual({ kind: "matched", id: "m1" });
    expect(index.match("BF-100")).toEqual({ kind: "matched", id: "m1" });
  });

  it("matches a file uploaded before Media.filename existed, from the path alone", () => {
    // `filename` is null; the backfill left the suffixed basename behind.
    const index = new FilenameIndex([
      { id: "m1", filename: null, storagePath: "biz-1/gallery/bf-100-x7k2m9.jpg" },
    ]);
    expect(index.match("bf-100.jpg")).toEqual({ kind: "matched", id: "m1" });
  });

  it("refuses a filename that names two files rather than picking one", () => {
    // `safeName` exists *because* two uploads called photo.jpg are normal, so
    // "the one called photo.jpg" is a question the library cannot answer.
    const index = new FilenameIndex([
      { id: "m1", filename: "photo.jpg", storagePath: "biz-1/gallery/photo-aaa111.jpg" },
      { id: "m2", filename: "photo.jpg", storagePath: "biz-1/gallery/photo-bbb222.jpg" },
    ]);
    expect(index.match("photo.jpg")).toEqual({ kind: "ambiguous", count: 2 });
  });

  it("reports an unknown filename as unmatched, not as an error", () => {
    const index = new FilenameIndex([]);
    expect(index.match("nothing.jpg")).toEqual({ kind: "unmatched" });
    expect(index.match("   ")).toEqual({ kind: "unmatched" });
  });

  it("counts one file once when its name and its path give the same key", () => {
    const index = new FilenameIndex([
      { id: "m1", filename: "bf-100.jpg", storagePath: "biz-1/gallery/bf-100.jpg" },
    ]);
    expect(index.match("bf-100.jpg")).toEqual({ kind: "matched", id: "m1" });
  });
});

describe("keysFor", () => {
  it("offers the real name before the derived one", () => {
    const keys = keysFor({
      id: "m1",
      filename: "Butterfly Valve.jpg",
      storagePath: "biz/gallery/butterfly-valve-x1y2z3.jpg",
    });
    expect(keys[0]).toBe("butterfly-valve.jpg");
    expect(keys).toContain("butterfly-valve");
  });
});

describe("splitFilenames", () => {
  it("splits a cell holding several, and never on a space", () => {
    expect(splitFilenames("a.jpg, b.jpg;c.jpg|d.jpg")).toEqual([
      "a.jpg",
      "b.jpg",
      "c.jpg",
      "d.jpg",
    ]);
    // `IMG 1234.jpg` is one filename.
    expect(splitFilenames("IMG 1234.jpg")).toEqual(["IMG 1234.jpg"]);
  });
});

describe("stemOf", () => {
  it("keeps a name that has no extension", () => {
    expect(stemOf("bf-100")).toBe("bf-100");
    expect(stemOf("bf-100.jpg")).toBe("bf-100");
  });
});
